name: Create Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build and upload release:

    runs-on: macos-14

    steps:
    - uses: actions/checkout@v4

    - name: Build Setup
      shell: bash
      run: >
       cmake . -B build
       -DCMAKE_BUILD_TYPE=RelWithDebInfo
       -DCMAKE_INSTALL_PREFIX=install

    - name: Build
      run: 	cmake --build build --target dawn -- -j4

    - name: Install
      run: 	cmake --install build

    - name: Upload to Releases
      run: |
        zip -r dawn-osx-arm.zip install
        tar -czvf dawn-osx-arm.tar.gz install
        gh release create ${{github.ref_name}} --generate-notes ./dawn-osx-arm.zip ./dawn-osx-arm.tar.gz
      env: 
        GITHUB_TOKEN: ${{ github.TOKEN }}
