name: Create Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'chromium/[0-9]+'

permissions:
  contents: write

jobs:
  build:

    runs-on: macos-14

    steps:
    - uses: actions/checkout@v4

    - name: Build Setup
      run: >
       cmake . -B build
       -DCMAKE_BUILD_TYPE=RelWithDebInfo
       -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64"
       -DCMAKE_INSTALL_PREFIX=install

    - name: Build
      run:  cmake --build build --target dawn -- -j4

    - name: Install
      run:  cmake --install build

    - name: Upload to Releases
      run: |
        tar -czvf dawn-osx-arm.tar.gz install
        gh release create ${{ github.ref_name }} --generate-notes ./dawn-osx-arm.tar.gz
      env: 
        GITHUB_TOKEN: ${{ github.TOKEN }}
