name: Build Artifacts and Upload To Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'chromium/[0-9]+'

permissions:
  contents: write

jobs:
  build:

    runs-on: macos-14

    steps:
    - uses: actions/checkout@v4

    - name: install Ninja
      run: brew install ninja

    - name: Build Setup
      run: make build-setup

    - name: Build
      run:  make build

    - name: Install
      run:  make install

    - name: Upload to Releases
      run: |
        tar -czvf dawn-osx-universal-relwithdebinfo+assert.tar.gz install/Debug
        tar -czvf dawn-osx-universal-release.tar.gz install/Release
        gh release create ${{ github.ref_name }} --generate-notes ./dawn-osx-universal-relwithdebinfo+assert.tar.gz ./dawn-osx-universal-release.tar.gz
      env: 
        GITHUB_TOKEN: ${{ github.TOKEN }}
